name: Auto-approve
on: pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - name: Auto-approve
      uses: hmarr/auto-approve-action@v2.1.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
